### PR TITLE
Finalize implementation of keepkey and add automated tests for it

### PR DESCRIPTION
**Pull request by achow101**
Implements the signmessage, displayaddress, and signtx commands for the keepkey. This also completes its implementation and the documentation is updated as such.

Note that because the Keepkey is a clone of the Trezor, these implementations are copies of the Trezor ones modified slightly to work with the Keepkey library.

This also adds an automated test for the KeepKey using the KeepKey simulator.

### CODE REVIEW

**Comment by instagibbs** [comment]
is this WIP?

**Comment by achow101** [comment]
> is this WIP?

Kind of. It's waiting on upstream changes. However I have finished everything else.

**Comment by achow101** [comment]
Upstream has fixed their issues (besides their versioning and PyPi problems) so this is ready for review now. Instead of splitting implementation and tests, I have decided to just make them one large pr as having tests make it easier to check that the implementation is correct.

**Comment by keepkeyjon** [comment]
I filed a few issues for things on our end that could be better:
https://github.com/keepkey/keepkey-firmware/issues/78
https://github.com/keepkey/python-keepkey/issues/40
https://github.com/keepkey/python-keepkey/issues/39

**Comment by instagibbs** [comment]
utACK

**Pull request merged**
