### PR TITLE
rename options to desctiptor-matching ones

### PR DESCRIPTION
**Pull request by instagibbs**
This makes it easier to support more address types in the future without having users guess as to what they are called.

### CODE REVIEW

**Comment by instagibbs** [comment]
rebased.

**Comment by achow101** [comment]
needs rebase

**Comment by instagibbs** [comment]
rebased. Make sure I didn't miss any renaming, in documentation or elsewhere.

**Comment by achow101** [comment]
utACK 26c57b33234b415a30911d792e65227c782620e8

**Pull request merged**
