### PR TITLE
implement display_address for digitalbitbox

### PR DESCRIPTION
**Pull request by fivepiece**
Displays the address of the pubkey at `keypath` on the command line.
Tested by generating descriptors for the different address types and running `getaddressinfo` on one of the addresses in the range.

```
# from imported descriptor :
# [{"range": {"start": 0, "end": 10}, "desc": "sh(wpkh([1fa45b69/49h/1h/0h]tpubDDj7yFRYtXaPR9UtCfVLJTyhwsCkhnkcb1xth6X2HbvFKMzWPxNcNjiJyT3HRbjn5KDYE3BpAwCDAeSN9GNSPooeF7ueSWDLZHR4QQCY8Ns/0/*))", "keypool": true, "internal": false, "timestamp": "now"}]

# 5th address in the range
$ ./hwi.py --testnet --password testnet --device-path 0003:000e:00 --device-type digitalbitbox displayaddress 'm/44h/1h/0h/0/5'
{"address": "mv1n2KkNMp1mkFFNmRXznEJHjdM1d5HzU1"}

$ bitcoin-cli -testnet -rpcwallet=dbb getaddressinfo mv1n2KkNMp1mkFFNmRXznEJHjdM1d5HzU1
{
  "address": "mv1n2KkNMp1mkFFNmRXznEJHjdM1d5HzU1",
  "scriptPubKey": "76a9149f053ff9055298aa1dbb731b9e47c1bd3665c83488ac",
  "ismine": false,
  "solvable": true,
  "desc": "pkh([1fa45b69/44'/1'/0'/0/5]02b48a7e7ca82671958e81d6d3a6a6f7e52c1be413b191d2b62cd331e27cd99d80)",
  "iswatchonly": true,
  "isscript": false,
  "iswitness": false,
  "pubkey": "02b48a7e7ca82671958e81d6d3a6a6f7e52c1be413b191d2b62cd331e27cd99d80",
  "iscompressed": true,
  "label": "",
  "ischange": false,
  "timestamp": 1296688602,
  "hdkeypath": "m/44'/1'/0'/0/5",
  "hdseedid": "0000000000000000000000000000000000000000",
  "hdmasterfingerprint": "1fa45b69",
  "labels": [
    {
      "name": "",
      "purpose": "receive"
    }
  ]
}

# from imported descriptor :
# [{"range": {"start": 0, "end": 10}, "desc": "sh(wpkh([1fa45b69/49h/1h/0h]tpubDDj7yFRYtXaPR9UtCfVLJTyhwsCkhnkcb1xth6X2HbvFKMzWPxNcNjiJyT3HRbjn5KDYE3BpAwCDAeSN9GNSPooeF7ueSWDLZHR4QQCY8Ns/0/*))", "keypool": true, "internal": false, "timestamp": "now"}]

$ ./hwi.py --testnet --password testnet --device-path 0003:000e:00 --device-type digitalbitbox displayaddress --sh_wpkh 'm/49h/1h/0h/0/5'
{"address": "2NByNrtRSTWwqzpSy73nrAhALNRZHGeHRWa"}

$ bitcoin-cli -testnet -rpcwallet=dbb getaddressinfo 2NByNrtRSTWwqzpSy73nrAhALNRZHGeHRWa
{         
  "address": "2NByNrtRSTWwqzpSy73nrAhALNRZHGeHRWa",
  "scriptPubKey": "a914cd6b24101a3d08dc9405bb4a588fd699b0db9ee887",
  "ismine": false,
  "solvable": true,
  "desc": "sh(wpkh([1fa45b69/49'/1'/0'/0/5]023cf9e800ccd325bff857cae5790ae4082c09138dd01ccfe6349903ad99e70227))",
  "iswatchonly": true,
  "isscript": true,
  "iswitness": false,
  "script": "witness_v0_keyhash",
  "hex": "0014f54ecd5d5126e5fd577cf199f51f76f51d6ff556",
  "pubkey": "023cf9e800ccd325bff857cae5790ae4082c09138dd01ccfe6349903ad99e70227",
  "embedded": {
    "isscript": false,
    "iswitness": true,
    "witness_version": 0,
    "witness_program": "f54ecd5d5126e5fd577cf199f51f76f51d6ff556",
    "pubkey": "023cf9e800ccd325bff857cae5790ae4082c09138dd01ccfe6349903ad99e70227",
    "address": "tb1q748v6h23ymjl64mu7xvl28mk75wkla2k662zd0",
    "scriptPubKey": "0014f54ecd5d5126e5fd577cf199f51f76f51d6ff556"
  }, 
  "label": "",
  "ischange": false,
  "timestamp": 1296688602,
  "hdkeypath": "m/49'/1'/0'/0/5",
  "hdseedid": "0000000000000000000000000000000000000000",
  "hdmasterfingerprint": "1fa45b69",
  "labels": [
    {
      "name": "",
      "purpose": "receive"
    }
  ]
}

# from imported descriptor :
# [{"internal": false, "keypool": true, "timestamp": "now", "range": {"end": 10, "start": 0}, "desc": "wpkh([1fa45b69/84h/1h/0h]tpubDCQbKDQ4U2UyTL6EJ6EMoRw2FFAtRdcVFmyrW889nmEFrXrNsdMtsYNaUM8GyPBVz3YYgKmQTCzUY8WARVB5CUyi7HqFSvMnj2VEUzB9X7e/0/*)"}]

$ ./hwi.py --testnet --password testnet --device-path 0003:000e:00 --device-type digitalbitbox displayaddress --wpkh 'm/84h/1h/0h/0/5'
{"address": "tb1qtdnh20pqwz0tp8rl9gc64s4qrreexeq0744vd7"}

$ bitcoin-cli -testnet -rpcwallet=dbb getaddressinfo tb1qtdnh20pqwz0tp8rl9gc64s4qrreexeq0744vd7
{
  "address": "tb1qtdnh20pqwz0tp8rl9gc64s4qrreexeq0744vd7",
  "scriptPubKey": "00145b67753c20709eb09c7f2a31aac2a018f393640f",
  "ismine": false,
  "solvable": true,
  "desc": "wpkh([1fa45b69/84'/1'/0'/0/5]039a411197fbf74cc436654e01af97e2a950e46938f5c841a0af666f844ebca3d7)",
  "iswatchonly": true,
  "isscript": false,
  "iswitness": true,
  "witness_version": 0,
  "witness_program": "5b67753c20709eb09c7f2a31aac2a018f393640f",
  "pubkey": "039a411197fbf74cc436654e01af97e2a950e46938f5c841a0af666f844ebca3d7",
  "label": "",
  "ischange": false,
  "timestamp": 1296688602,
  "hdkeypath": "m/84'/1'/0'/0/5",
  "hdseedid": "0000000000000000000000000000000000000000",
  "hdmasterfingerprint": "1fa45b69",
  "labels": [
    {
      "name": "",
      "purpose": "receive"
    }
  ]
}
```

### CODE REVIEW

**Comment by achow101** [comment]
I'm leaning towards a NACK on this one. The Digital BitBox doesn't have a display which was the whole point of displayaddress. It's supposed to show you the address on the device itself to avoid problems where malware shows you a different address on the machine. I don't think we should implement displayaddress for the bitbox and rather just say that it isn't supported (which is what I have done in #84)

**Comment by instagibbs** [comment]
I'm NACKish on this as well. This shouldn't be a general tool from going from xpub->address, but for displaying it on the trusted device.

**Comment by fivepiece** [comment]
I see, but there are other things that get posted to the command line like `getxpub` and even the result of `getkeypool` which the malware could technically also hijack.
There isn't really another solution for the dbb that I can think of except for using the 2FA android app that acts as a screen, but that requires using dbb's own software, internet connection and other annoyances.

I'll understand if you're still against this.  Let me know and I'll close this if so.

**Comment by achow101** [comment]
> I see, but there are other things that get posted to the command line like `getxpub` and even the result of `getkeypool` which the malware could technically also hijack.

Certainly, but the point of display address is to be a kind of man in the middle protection. You can use `getxpub` and `getkeypool`, then use display address and check that whatever pubkey or descriptor you get back is actually from the device. Since the Bitbox doesn't have a screen, we can't do this and IMO displaying only on the command line would break the purpose of display address. I think it would be possible to do it with the 2FA app, but I don't know how that works and I haven't really looked into it.

**Comment by fivepiece** [comment]
Alright, thanks for taking the time to look into the PR :)

Closing -

**Pull request closed without merging**
