### PR TITLE
Refactor to actually be useful as a library

### PR DESCRIPTION
**Pull request by achow101**
Refactors `command.py` so that it just has the functions for each command and the arguments are the actual arguments for the command instead of `args` and `client`. `process_commands` has been moved to `cli.py` along with the handlers that take `args` and `client` which then call the functions in `commands.py` to do the command.

`setup.py` has been updated to also install a `hwi` executable script and the version number is bumped to 0.0.5.

This makes HWI actually usable as a library while also having the command line functionality.

Completes part 1 of #91

### CODE REVIEW

**Comment by achow101** [comment]
Had to rebase

**Comment by achow101** [comment]
Fixed the error

**Comment by Sjors** [comment]
Concept ACK. But let's use named arguments, especially for `getkeypool(client, args.path, args.start, args.end, args.internal, args.keypool, args.account, args.sh_wpkh, args.wpkh)`. That makes it easier for me in #73 to pass in a descriptor, without having to explicitly set `args.path`, `args.sh_wpkh`, etc to null.

**Comment by Sjors** [comment]
The latter. It's probably fine to keep some arguments like `client` positional.

**Comment by achow101** [comment]
@Sjors Done.

**Comment by achow101** [comment]
Seems like a spurious failure. I restarted the travis build and it seems fine now

**Comment by Sjors** [comment]
tACK 8e4b3fc (based on testing #73, which I just rebased)

**Pull request merged**
